#index:
#    path: /
#    controller: App\Controller\DefaultController::index

sum_exercise:
  path: /sum/{value1}/{value2}
  # the controller value has the format 'controller_class::method_name'
  requirements:
    value1: '\d+'
    value2: '\d+'
  controller: App\Controller\MathController::sum
  methods:
    - GET